/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // GraalVM plugin for generating native binaries
    id("org.graalvm.buildtools.native") version "0.10.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // PicoCLI dependency for creating command-line tools
    implementation("info.picocli:picocli:4.7.5")
    // PicoCLI annotation processor for code generation
    annotationProcessor("info.picocli:picocli-codegen:4.7.5")
    // JUnit testing framework
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "cl.playground.cli.CommandLineApp"
}

graalvmNative {
    // Configuration for native compilation
    binaries {
        named("main") {
            imageName.set("sqlift") // Native binary name
            buildArgs.addAll(
                "--no-fallback", // Do not generate fallback image based on JVM
                "--enable-all-security-services", // Enable all security services
                "--report-unsupported-elements-at-runtime" // Report unsupported elements at runtime
            )
        }
    }
}

tasks.test {
    // Use the JUnit Platform framework for testing
    useJUnitPlatform()
}
